### ISSUE TITLE
Permit simple ON / OFF on climate entities

### ISSUE THREAD

**Issue by submarcos** [gduteil/cozytouch#23]
Hi, and Thank you very much for your job.

Your integration is perfect to manage my Kelud 1750W Anthracite Standard.

However, Internal temperature and climate is not very accurate and I wish create my own thermostat with external temperature, other sensor in room, real window detection, etc (with custom climate or versatile thermostat)

There is no ON / OFF button that I can use to handle this (but there is min and max temperature, that is very cool).

Is-it possible to add this feature ?

Thank you very much

**Comment by atmadja40** [comment]
Hello submarcos,
Can you please show us the content of your cozytouch.json file ?
And also show us how the climate entity looks like ?

**Comment by gduteil** [comment]
Hi,

I don't remember if Cozytouch protocol has this parameter, do you have ON/OFF mode in the official mobile app ?
If not, a way could be to play with other parameters (requested temperature) to trigger ON of OFF

**Comment by hobbe** [comment]
Hi @submarcos 

Adding a switch would add complexity to the integration. A "climate" is not really a ON/OFF device.

You can use the action builder to trigger the ON and OFF actions in a `script`, an `automation`, a `switch helper` or a `button` on the dashboard.

![Image](https://github.com/user-attachments/assets/c7dd942e-e73f-45eb-9fda-cd480254e32a)


Or YAML script:

```yaml
towel_rack_on:
  alias: Turn on towel rack
  description: ""
  sequence:
    - action: climate.turn_on
      entity_id: climate.seche_serviettes_chauffage
```
